spring  :
   kafka :
    consumer :
      bootstrap-servers : localhost:9092
      group-id: kafka-consumer-default-group-id
      key-deserializer : org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: "com.springboot"
    listener:
       concurrency: 5


server :
    port : 9292